### ISSUE TITLE
Sleeves Memory Leak

### ISSUE THREAD

**Issue by ZMLawliet** [Silverfeelin/Starbound-OutfitGenerator#3] opened 2017-04-18 03:20 UTC
As another thread mentioned; Sleeve items suffer from intense memory leak issues. Wearing a sleeve item will slowly eat away at all available RAM until the game simply crashes. 

Certainly deserves some investigation; though I understand it may be difficult to resolve given the modding access level.

**Comment by Silverfeelin** [comment] 2017-04-18 13:59
Duplicate of https://github.com/Silverfeelin/Starbound-OutfitGenerator/issues/1.

Please don't open duplicate entries. Instead, you can add comments to existing issues.  
I have added a new comment to the other opened issue, in regard to this post.

**Closed as completed by Silverfeelin** 2017-04-18 13:59 UTC
Labels: duplicate
